const express = require('express')
const app = express()
const port =  process.env.PORT || 4000
const dbConnection = require ('./db')
app.use(express.json())
app.use('/api/admins/' , require('./controller/adminsController'))
app.use('/api/flats/' , require('./controller/flatsController'))
app.use('/api/users/' , require('./controller/usersController'))
app.get('/',(req, res)=> res.send ('Hello!'))
app.listen(port, ()=> console.log('Node Js Server Started in ' + port))